export const GenderOptions = ["Male", "Female", "Other"];

export const PatientFormDefaultValues = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  birthDate: new Date(Date.now()),
  gender: "Male" as Gender,
  address: "",
  occupation: "",
  emergencyContactName: "",
  emergencyContactNumber: "",
  primaryPhysician: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "Birth Certificate",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};

export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Resident Alien Card (Green Card)",
  "Social Security Card",
  "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const Doctors = [
  {
    image: "/assets/images/dr-green.png",
    name: "John Green",
    degree: "Cardiologist, MD",
    address: "1347 Pine Street, San Francisco, CA 94111",
    rating: 4.8,
    insuranceAccepted: ["Aetna", "Blue Cross Blue Shield", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-cameron.png",
    name: "Leila Cameron",
    degree: "Pediatrician, DO",
    address: "820 Maple Avenue, Austin, TX 78701",
    rating: 4.6,
    insuranceAccepted: ["Cigna", "Aetna", "Humana"],
  },
  {
    image: "/assets/images/dr-livingston.png",
    name: "David Livingston",
    degree: "Orthopedic Surgeon, MD",
    address: "412 Rose Blvd, Chicago, IL 60616",
    rating: 4.9,
    insuranceAccepted: ["UnitedHealthcare", "Kaiser Permanente", "Blue Shield"],
  },
  {
    image: "/assets/images/dr-peter.png",
    name: "Evan Peter",
    degree: "Neurologist, MD",
    address: "223 Sunset Road, Miami, FL 33133",
    rating: 4.7,
    insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Aetna"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Jane Powell",
    degree: "Family Medicine, MD",
    address: "5909 Elm Street, Seattle, WA 98101",
    rating: 4.5,
    insuranceAccepted: ["Humana", "Medicare", "Aetna"],
  },
  {
    image: "/assets/images/dr-remirez.png",
    name: "Alex Ramirez",
    degree: "Dermatologist, MD",
    address: "783 Birch Lane, Denver, CO 80203",
    rating: 4.4,
    insuranceAccepted: ["Cigna", "UnitedHealthcare", "Blue Cross"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Jasmine Lee",
    degree: "Psychiatrist, MD",
    address: "1580 Ocean Drive, Los Angeles, CA 90015",
    rating: 4.9,
    insuranceAccepted: ["Kaiser Permanente", "Blue Cross Blue Shield", "Cigna"],
  },
  {
    image: "/assets/images/dr-cruz.png",
    name: "Alyana Cruz",
    degree: "Gynecologist, MD",
    address: "95 Beacon Street, Boston, MA 02108",
    rating: 4.6,
    insuranceAccepted: ["Aetna", "UnitedHealthcare", "Humana"],
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Hardik Sharma",
    degree: "Internal Medicine, MD",
    address: "301 Willow Avenue, New York, NY 10029",
    rating: 4.8,
    insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Medicaid"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "John Green",
    degree: "Cardiologist, MD",
    address: "1347 Pine Street, San Francisco, CA 94111",
    rating: 4.8,
    insuranceAccepted: ["Aetna", "Blue Cross Blue Shield", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "Leila Cameron",
    degree: "Pediatrician, DO",
    address: "820 Maple Avenue, Austin, TX 78701",
    rating: 4.6,
    insuranceAccepted: ["Cigna", "Aetna", "Humana"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "David Livingston",
    degree: "Orthopedic Surgeon, MD",
    address: "412 Rose Blvd, Chicago, IL 60616",
    rating: 4.9,
    insuranceAccepted: ["UnitedHealthcare", "Kaiser Permanente", "Blue Shield"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "Evan Peter",
    degree: "Neurologist, MD",
    address: "223 Sunset Road, Miami, FL 33133",
    rating: 4.7,
    insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Aetna"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "Jane Powell",
    degree: "Family Medicine, MD",
    address: "5909 Elm Street, Seattle, WA 98101",
    rating: 4.5,
    insuranceAccepted: ["Humana", "Medicare", "Aetna"],
  },
  {
    image: "/assets/images/dr-remirez.png",
    name: "Alex Ramirez",
    degree: "Dermatologist, MD",
    address: "783 Birch Lane, Denver, CO 80203",
    rating: 4.4,
    insuranceAccepted: ["Cigna", "UnitedHealthcare", "Blue Cross"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Jasmine Lee",
    degree: "Psychiatrist, MD",
    address: "1580 Ocean Drive, Los Angeles, CA 90015",
    rating: 4.9,
    insuranceAccepted: ["Kaiser Permanente", "Blue Cross Blue Shield", "Cigna"],
  },
  {
    image: "/assets/images/dr-cruz.png",
    name: "Alyana Cruz",
    degree: "Gynecologist, MD",
    address: "95 Beacon Street, Boston, MA 02108",
    rating: 4.6,
    insuranceAccepted: ["Aetna", "UnitedHealthcare", "Humana"],
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Hardik Sharma",
    degree: "Internal Medicine, MD",
    address: "301 Willow Avenue, New York, NY 10029",
    rating: 4.8,
    insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Medicaid"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "Rebecca Williams",
    degree: "Endocrinologist, MD",
    address: "448 Oakwood Ave, Minneapolis, MN 55407",
    rating: 4.7,
    insuranceAccepted: ["Humana", "Aetna", "Cigna"],
  },
  {
    image: "/assets/images/dr-green.png",
    name: "Connor Murphy",
    degree: "Urologist, MD",
    address: "112 Lakeview Rd, Orlando, FL 32803",
    rating: 4.5,
    insuranceAccepted: ["UnitedHealthcare", "Blue Cross", "Kaiser Permanente"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Akira Tanaka",
    degree: "Oncologist, MD",
    address: "902 Ash Lane, Portland, OR 97205",
    rating: 4.9,
    insuranceAccepted: ["Cigna", "Medicare", "Blue Cross Blue Shield"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Rachel Wilson",
    degree: "Pulmonologist, MD",
    address: "203 Sycamore St, Atlanta, GA 30303",
    rating: 4.6,
    insuranceAccepted: ["Humana", "Kaiser Permanente", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Vikram Chopra",
    degree: "Gastroenterologist, MD",
    address: "6105 Riverbend Dr, Houston, TX 77004",
    rating: 4.8,
    insuranceAccepted: ["Aetna", "Blue Cross", "Medicare"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Laura Anderson",
    degree: "Rheumatologist, MD",
    address: "77 Ivy Road, Salt Lake City, UT 84105",
    rating: 4.4,
    insuranceAccepted: ["Cigna", "Aetna", "Blue Cross Blue Shield"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Omar Nasser",
    degree: "Ophthalmologist, MD",
    address: "198 Cherry Hill Ln, Philadelphia, PA 19103",
    rating: 4.7,
    insuranceAccepted: ["UnitedHealthcare", "Humana", "Kaiser Permanente"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Elijah Jackson",
    degree: "Allergist/Immunologist, MD",
    address: "921 Forest Ave, Charlotte, NC 28203",
    rating: 4.5,
    insuranceAccepted: ["Blue Cross Blue Shield", "Aetna", "Cigna"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Priya Kapoor",
    degree: "Hematologist, MD",
    address: "405 Redwood Blvd, San Jose, CA 95112",
    rating: 4.8,
    insuranceAccepted: ["Medicare", "Cigna", "Humana"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Miles Cooper",
    degree: "Anesthesiologist, MD",
    address: "312 Palm Avenue, Tampa, FL 33606",
    rating: 4.6,
    insuranceAccepted: ["Kaiser Permanente", "UnitedHealthcare", "Blue Cross"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Sana Khan",
    degree: "Nephrologist, MD",
    address: "101 Meadow Drive, Columbus, OH 43215",
    rating: 4.8,
    insuranceAccepted: ["Cigna", "Aetna", "Medicare"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Michael Brown",
    degree: "Plastic Surgeon, MD",
    address: "2218 Highland Ave, Birmingham, AL 35205",
    rating: 4.7,
    insuranceAccepted: ["UnitedHealthcare", "Blue Cross", "Humana"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Minh Nguyen",
    degree: "Otolaryngologist (ENT), MD",
    address: "34 Orchard Street, San Diego, CA 92101",
    rating: 4.6,
    insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Aetna"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Kavya Patel",
    degree: "Obstetrician, MD",
    address: "909 Sunrise Blvd, Sacramento, CA 95825",
    rating: 4.9,
    insuranceAccepted: ["Aetna", "Humana", "Medicare"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Carlos Rodriguez",
    degree: "Sports Medicine, DO",
    address: "450 Mission Street, San Jose, CA 95134",
    rating: 4.5,
    insuranceAccepted: ["Cigna", "UnitedHealthcare", "Blue Cross"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Hana Kim",
    degree: "Radiologist, MD",
    address: "378 Beacon Road, Richmond, VA 23220",
    rating: 4.8,
    insuranceAccepted: [
      "Humana",
      "Blue Cross Blue Shield",
      "Kaiser Permanente",
    ],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Richard Thomas",
    degree: "Pathologist, MD",
    address: "789 Holloway St, Newark, NJ 07102",
    rating: 4.4,
    insuranceAccepted: ["UnitedHealthcare", "Medicare", "Cigna"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Sophia White",
    degree: "Occupational Medicine, DO",
    address: "92 Greenfield Ave, Raleigh, NC 27601",
    rating: 4.6,
    insuranceAccepted: ["Aetna", "Blue Cross", "Humana"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Miguel Martinez",
    degree: "Infectious Disease Specialist, MD",
    address: "1255 University Way, Tallahassee, FL 32304",
    rating: 4.7,
    insuranceAccepted: ["Cigna", "Blue Cross Blue Shield", "Medicare"],
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Emily Hughes",
    degree: "Geriatrician, MD",
    address: "84 Park Blvd, Phoenix, AZ 85004",
    rating: 4.9,
    insuranceAccepted: ["Medicare", "UnitedHealthcare", "Aetna"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Rohit Mehta",
    degree: "Pain Management, MD",
    address: "1102 Vine Street, Cincinnati, OH 45202",
    rating: 4.5,
    insuranceAccepted: ["Kaiser Permanente", "Humana", "Cigna"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Sarah Davis",
    degree: "Emergency Medicine, MD",
    address: "303 W Main St, Boise, ID 83702",
    rating: 4.6,
    insuranceAccepted: ["Blue Cross", "Aetna", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Daniel Yang",
    degree: "Hepatologist, MD",
    address: "650 Harmony Blvd, Madison, WI 53703",
    rating: 4.7,
    insuranceAccepted: ["Humana", "Medicare", "Cigna"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Fatima Ali",
    degree: "Pulmonary Critical Care, MD",
    address: "4749 Forest Hills Rd, Nashville, TN 37203",
    rating: 4.8,
    insuranceAccepted: ["Aetna", "Blue Cross Blue Shield", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Gregory Hamilton",
    degree: "Nuclear Medicine, MD",
    address: "908 Ivy Lane, Des Moines, IA 50309",
    rating: 4.4,
    insuranceAccepted: ["Medicare", "Kaiser Permanente", "Cigna"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Naomi Joseph",
    degree: "Clinical Geneticist, MD",
    address: "625 Eastside Ave, Charleston, SC 29403",
    rating: 4.9,
    insuranceAccepted: ["Blue Cross", "Cigna", "UnitedHealthcare"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Benjamin Henderson",
    degree: "Colorectal Surgeon, MD",
    address: "77 Westwood Blvd, Omaha, NE 68106",
    rating: 4.6,
    insuranceAccepted: ["Humana", "Blue Cross", "Medicare"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Shruti Raman",
    degree: "Osteopathic Physician, DO",
    address: "456 Jasmine Dr, Oklahoma City, OK 73102",
    rating: 4.5,
    insuranceAccepted: ["Aetna", "UnitedHealthcare", "Kaiser Permanente"],
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Imran Abbas",
    degree: "Palliative Care, MD",
    address: "355 Redwood Circle, Anchorage, AK 99501",
    rating: 4.7,
    insuranceAccepted: ["Cigna", "Blue Cross Blue Shield", "Medicaid"],
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Clara Hart",
    degree: "Rehabilitation Medicine, MD",
    address: "1891 Boulder Rd, Helena, MT 59601",
    rating: 4.6,
    insuranceAccepted: ["UnitedHealthcare", "Aetna", "Humana"],
  },
  [
    {
      image: "/assets/images/dr-sharma.png",
      name: "Isabella Mendez",
      degree: "Sleep Medicine, MD",
      address: "1220 Harbor St, Santa Barbara, CA 93101",
      rating: 4.8,
      insuranceAccepted: ["Aetna", "Cigna", "UnitedHealthcare"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Nathan Moore",
      degree: "Vascular Surgeon, MD",
      address: "660 Windmere Dr, Billings, MT 59102",
      rating: 4.7,
      insuranceAccepted: ["Humana", "Kaiser Permanente", "Medicare"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Grace Lin",
      degree: "Pediatric Endocrinologist, MD",
      address: "2132 Lakefront Ave, Madison, WI 53704",
      rating: 4.9,
      insuranceAccepted: ["Cigna", "Blue Cross Blue Shield", "Medicaid"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Lucas Collins",
      degree: "Immunologist, MD",
      address: "897 Sandhill Rd, Santa Fe, NM 87501",
      rating: 4.6,
      insuranceAccepted: ["Aetna", "UnitedHealthcare", "Cigna"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Ritika Bhatt",
      degree: "Neonatologist, MD",
      address: "544 Redwood Avenue, Palo Alto, CA 94301",
      rating: 4.8,
      insuranceAccepted: ["Blue Cross", "Medicare", "Aetna"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Stephen Miller",
      degree: "Gastrointestinal Surgeon, MD",
      address: "300 Coral Reef Rd, Key West, FL 33040",
      rating: 4.5,
      insuranceAccepted: ["UnitedHealthcare", "Humana", "Cigna"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Olivia Foster",
      degree: "Speech-Language Pathologist, CCC-SLP",
      address: "872 Broadway Blvd, Kansas City, MO 64105",
      rating: 4.7,
      insuranceAccepted: ["Blue Cross", "Aetna", "Cigna"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Brian Sanders",
      degree: "Occupational Therapist, OTR/L",
      address: "9872 Elmwood St, Fargo, ND 58103",
      rating: 4.6,
      insuranceAccepted: ["Humana", "Cigna", "Blue Cross Blue Shield"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Chloe Abbott",
      degree: "Chiropractor, DC",
      address: "200 Mountain View Rd, Boulder, CO 80302",
      rating: 4.8,
      insuranceAccepted: ["Medicare", "Blue Cross", "Aetna"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Tariq Syed",
      degree: "Infectious Disease Specialist, MD",
      address: "99 Grand Ave, Jersey City, NJ 07302",
      rating: 4.7,
      insuranceAccepted: ["Cigna", "UnitedHealthcare", "Blue Cross"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Victoria Keller",
      degree: "Ophthalmic Surgeon, MD",
      address: "1451 Marina Way, Long Beach, CA 90802",
      rating: 4.9,
      insuranceAccepted: ["Aetna", "Medicare", "Humana"],
    },
    {
      image: "/assets/images/dr-sharma.png",
      name: "Ananya Das",
      degree: "Reproductive Endocrinologist, MD",
      address: "1150 Oak Grove Dr, Pasadena, CA 91104",
      rating: 4.8,
      insuranceAccepted: [
        "Cigna",
        "UnitedHealthcare",
        "Blue Cross Blue Shield",
      ],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Zachary Mitchell",
      degree: "Medical Geneticist, MD",
      address: "470 Franklin Blvd, Eugene, OR 97403",
      rating: 4.7,
      insuranceAccepted: ["Blue Cross", "Kaiser Permanente", "Medicaid"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Lucia Alvarez",
      degree: "Dermatopathologist, MD",
      address: "812 Jasmine Court, El Paso, TX 79912",
      rating: 4.6,
      insuranceAccepted: ["Aetna", "Cigna", "Humana"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Kevin Wong",
      degree: "Medical Oncologist, MD",
      address: "650 Summit View Dr, Reno, NV 89501",
      rating: 4.9,
      insuranceAccepted: ["UnitedHealthcare", "Blue Cross", "Medicare"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Nadia Hassan",
      degree: "Pediatric Cardiologist, MD",
      address: "1345 River Rd, Baton Rouge, LA 70802",
      rating: 4.7,
      insuranceAccepted: ["Cigna", "Humana", "Aetna"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Dominic Richards",
      degree: "Anesthesiologist, MD",
      address: "2409 Pearl St, Boulder, CO 80302",
      rating: 4.6,
      insuranceAccepted: ["Blue Cross Blue Shield", "Cigna", "Medicare"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Emi Murakami",
      degree: "Pediatric Neurologist, MD",
      address: "5989 Capitol Ave, Cheyenne, WY 82001",
      rating: 4.8,
      insuranceAccepted: ["UnitedHealthcare", "Aetna", "Blue Cross"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Samuel Holt",
      degree: "Trauma Surgeon, MD",
      address: "1998 Ironwood Dr, Little Rock, AR 72202",
      rating: 4.5,
      insuranceAccepted: ["Cigna", "Medicare", "Blue Cross"],
    },
    {
      image: "/assets/images/dr-cruz.png",
      name: "Reema Shah",
      degree: "Pulmonologist, MD",
      address: "6785 Bayfront Dr, Sarasota, FL 34236",
      rating: 4.9,
      insuranceAccepted: ["Aetna", "Kaiser Permanente", "Cigna"],
    },
  ],
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  canceled: "/assets/icons/cancelled.svg",
};
